analyzer:
  exclude:
    - lib/data/database/database.g.dart
  plugins:
    - dart_code_metrics
  errors:
    always_declare_return_types: warning
    always_put_control_body_on_new_line: warning
    always_put_required_named_parameters_first: warning
    always_use_package_imports: warning
    avoid_classes_with_only_static_members: warning
    avoid_dynamic_calls: warning
    avoid_empty_else: warning
    avoid_field_initializers_in_const_classes: warning
    avoid_multiple_declarations_per_line: warning
    avoid_null_checks_in_equality_operators: warning
    avoid_print: error
    avoid_redundant_argument_values: warning
    avoid_relative_lib_imports: warning
    avoid_return_types_on_setters: warning
    avoid_returning_null_for_future: warning
    avoid_returning_this: warning
    avoid_shadowing_type_parameters: warning
    avoid_single_cascade_in_expression_statements: warning
    avoid_slow_async_io: warning
    avoid_unnecessary_containers: warning
    avoid_unused_constructor_parameters: warning
    await_only_futures: warning
    camel_case_extensions: warning
    camel_case_types: warning
    cast_nullable_to_non_nullable: warning
    constant_identifier_names: warning
    curly_braces_in_flow_control_structures: warning
    deprecated_consistency: warning
    directives_ordering: warning
    do_not_use_environment: warning
    empty_catches: ignore
    empty_constructor_bodies: warning
    empty_statements: warning
    enable_null_safety: error
    exhaustive_cases: warning
    file_names: error
    flutter_style_todos: warning
    implementation_imports: warning
    implicit_call_tearoffs: warning
    library_names: warning
    library_prefixes: warning
    library_private_types_in_public_api: warning
    lines_longer_than_80_chars: warning
    no_duplicate_case_values: warning
    no_logic_in_create_state: warning
    no_runtimeType_toString: warning
    non_constant_identifier_names: error
    noop_primitive_operations: warning
    null_check_on_nullable_type_parameter: warning
    null_closures: warning
    omit_local_variable_types: ignore
    overridden_fields: warning
    package_api_docs: warning
    package_names: warning
    package_prefixed_library_names: warning
    parameter_assignments: warning
    prefer_asserts_with_message: warning
    prefer_const_constructors_in_immutables: warning
    prefer_const_declarations: warning
    prefer_const_literals_to_create_immutables: warning
    prefer_constructors_over_static_methods: warning
    prefer_contains: warning
    prefer_equal_for_default_values: warning
    prefer_expression_function_bodies: warning
    prefer_final_fields: warning
    prefer_final_locals: warning
    prefer_final_parameters: warning
    prefer_foreach: warning
    prefer_function_declarations_over_variables: warning
    prefer_if_null_operators: warning
    prefer_initializing_formals: warning
    prefer_inlined_adds: warning
    prefer_is_not_empty: warning
    prefer_is_not_operator: warning
    prefer_iterable_whereType: warning
    prefer_mixin: warning
    prefer_null_aware_method_calls: warning
    prefer_null_aware_operators: warning
    prefer_single_quotes: error
    prefer_spread_collections: warning
    prefer_typing_uninitialized_variables: warning
    prefer_void_to_null: warning
    provide_deprecation_message: warning
    public_member_api_docs: ignore
    recursive_getters: warning
    require_trailing_commas: warning
    sized_box_for_whitespace: warning
    slash_for_doc_comments: warning
    sort_child_properties_last: warning
    sort_constructors_first: warning
    sort_pub_dependencies: warning
    sort_unnamed_constructors_first: warning
    unawaited_futures: error
    unnecessary_await_in_return: warning
    unnecessary_brace_in_string_interps: warning
    unnecessary_const: warning
    unnecessary_getters_setters: warning
    unnecessary_lambdas: warning
    unnecessary_new: error
    unnecessary_null_aware_assignments: warning
    unnecessary_null_checks: error
    unnecessary_null_in_if_null_operators: warning
    unnecessary_nullable_for_final_variable_declarations: warning
    unnecessary_overrides: warning
    unnecessary_parenthesis: warning
    unnecessary_raw_strings: warning
    unnecessary_statements: warning
    unnecessary_string_escapes: warning
    unnecessary_string_interpolations: warning
    unnecessary_this: warning
    unrelated_type_equality_checks: error
    unsafe_html: warning
    use_build_context_synchronously: warning
    use_enums: warning
    use_full_hex_values_for_flutter_colors: warning
    use_function_type_syntax_for_parameters: warning
    use_if_null_to_convert_nulls_to_bools: warning
    use_is_even_rather_than_modulo: warning
    use_key_in_widget_constructors: warning
    use_late_for_private_fields_and_variables: warning
    use_named_constants: warning
    use_raw_strings: warning
    use_rethrow_when_possible: warning
    use_setters_to_change_properties: warning
    use_string_buffers: warning
    use_test_throws_matchers: warning
    use_to_and_as_if_applicable: warning
    valid_regexps: warning
    void_checks: warning


  language:
    strict-casts: true
    strict-inference: true


# https://dart-lang.github.io/linter/lints/
linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - avoid_classes_with_only_static_members
    - avoid_dynamic_calls
    - avoid_empty_else
    - avoid_field_initializers_in_const_classes
    - avoid_multiple_declarations_per_line
    - avoid_null_checks_in_equality_operators
    - avoid_print
    - avoid_redundant_argument_values
    - avoid_relative_lib_imports
    - avoid_return_types_on_setters
    - avoid_returning_null_for_future
    - avoid_returning_this
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_slow_async_io
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cast_nullable_to_non_nullable
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - deprecated_consistency
    - directives_ordering
    - do_not_use_environment
    - empty_catches
    - empty_constructor_bodies
    - empty_statements
    - enable_null_safety
    - exhaustive_cases
    - file_names
    - flutter_style_todos
    - implementation_imports
    - implicit_call_tearoffs
    - library_names
    - library_prefixes
    - library_private_types_in_public_api
    - lines_longer_than_80_chars
    - no_duplicate_case_values
    - no_logic_in_create_state
    - no_runtimeType_toString
    - non_constant_identifier_names
    - noop_primitive_operations
    - null_check_on_nullable_type_parameter
    - null_closures
    - omit_local_variable_types
    - overridden_fields
    - package_api_docs
    - package_names
    - package_prefixed_library_names
    - parameter_assignments
    - prefer_asserts_with_message
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_constructors_over_static_methods
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_expression_function_bodies
    - prefer_final_fields
    - prefer_final_locals
    - prefer_final_parameters
    - prefer_foreach
    - prefer_function_declarations_over_variables
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_typing_uninitialized_variables
    - prefer_void_to_null
    - provide_deprecation_message
    - public_member_api_docs
    - recursive_getters
    - require_trailing_commas
    - sized_box_for_whitespace
    - slash_for_doc_comments
    - sort_child_properties_last
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unrelated_type_equality_checks
    - unsafe_html
    - use_build_context_synchronously
    - use_enums
    - use_full_hex_values_for_flutter_colors
    - use_function_type_syntax_for_parameters
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_raw_strings
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    - valid_regexps
    - void_checks

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  metrics-exclude:
    - test/**
  rules:
    - avoid-dynamic
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    #- avoid-nested-conditional-expressions
    - newline-before-return
    - no-boolean-literal-compare
    - no-empty-block
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
    - prefer-moving-to-variable
    - avoid-non-null-assertion